apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-webapp-ingress
  namespace: k8s-webapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - k8s-webapp.local
      secretName: k8s-webapp-tls


  rules:
    - host: k8s-webapp.local
      http:
        paths:
          # Frontend : toutes les routes (/, /tasks, etc.)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

          # Backend : /api â†’ service backend
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
